### ISSUE TITLE
Having children with `GlobalKey` crashes since 2.0.1

### ISSUE THREAD

**Issue by oO0oO0oO0o0o00** [caduandrade/multi_split_view#58]
The bug was introduced in `deb0f87` which fixes local keys not working. When global keys are used, there's no need to pass them to wrapper views since they are global.

Reproduce:
1. Create empty app project (optionally).
2. Replace main.dart with coed below:
```dart
import 'package:flutter/material.dart';
import 'package:multi_split_view/multi_split_view.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: S(),
      ),
    );
  }
}

class S extends StatefulWidget {
  const S({super.key});
  @override
  State<StatefulWidget> createState() => SS();
}

class SS extends State<S> {
  final k = GlobalKey();

  @override
  Widget build(BuildContext context) {
    return MultiSplitView(children: [const Text('Hello World!'), TextField(key: k)]);
  }
}
```
3. Add dependency:
```yaml
dependencies:
  flutter:
    sdk: flutter
  multi_split_view:
    git:
        url: https://github.com/caduandrade/multi_split_view.git
        ref: deb0f87d5ac86623a15b19bcf7a65f9d74edafda
```
4. Run and observe the crash.
5. Change the ref to its parent and rerun without problem.

Potential fix: 
In lib/src/multi_split_view.dart:655
```diff
- key: child.key,
+ key: child.key is GlobalKey ? null : child.key,
```
